export const USER = 'USER_ENTITY';
export const REPO = 'REPO_ENTITY';
export const FOLLOWERS = 'FOLLOWERS_ENTITY';
export const FOLLOWINGS = 'FOLLOWINGS_ENTITY';
export const STARGAZERS = 'STARGAZERS_ENTITY';
export const USER_REPOS = 'USER_REPOS';
export const REPO_SUBSCRIBERS = 'REPO_SUBSCRIBERS';
